# Generated by Django 5.0.6 on 2024-06-01 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='Author',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='Content',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='Created_date',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='Title',
            new_name='title',
        ),
    ]
