# Generated by Django 5.0.6 on 2024-06-08 17:07

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Başlıq')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Məzmun')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Yaradılan tarix')),
                ('image', models.FileField(blank=True, null=True, upload_to='Article image', verbose_name='Şəkil')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Yazar')),
            ],
        ),
    ]
